### ISSUE TITLE
ShinebugReactor_2024-07-24 NullReference exception

### ISSUE THREAD

**Issue by kirill-stepanoff** [alena-karnauhova/ONI-Mods#2]
after updating mod to ShinebugReactor_2024-07-24
I got crash on unpausing

- Both SpacedOut and FrostyPlanet DLC installed and active:
- Mod settings are default

STR:

1. Load save with constructed reactor loaded with shine bugs (there are 60 bugs inside, and no eggs)
2. Unpause game

Was working before mod update

```
NullReferenceException: Object reference not set to an instance of an object

ShinebugReactor.ShinebugSimulator.get_Data () (at <1d797ed294ae45dc9a639230f9e00696>:0)
ShinebugReactor.ShinebugReactor.EnergySim200ms (System.Single dt) (at <1d797ed294ae45dc9a639230f9e00696>:0)
EnergySim.EnergySim200ms (System.Single dt) (at <ac8788b5d0fb4b89a20068ab3b6a25de>:0)
Game.StepTheSim (System.Single dt) (at <ac8788b5d0fb4b89a20068ab3b6a25de>:0)
Game.UnsafeSim200ms (System.Single dt) (at <ac8788b5d0fb4b89a20068ab3b6a25de>:0)
Game.SimEveryTick (System.Single dt) (at <ac8788b5d0fb4b89a20068ab3b6a25de>:0)
Game.Update () (at <ac8788b5d0fb4b89a20068ab3b6a25de>:0)
```

**Comment by kirill-stepanoff** [comment]
Same save works after reverting mod to previous release

**Comment by alena-karnauhova** [comment]
New version seems to be incompatible with previous versions saves. Added migration version to releases. Load and re-save an old save with it, then you should be fine with the new version.
